# -*- mode: k8s -*-

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  
spec:
  # selector defines the pods that are in the service
  selector:
    app: webapp
    release: "0"

  ports:
    - name: http
      port: 80
      nodePort: 30080 

  # type ClusterIP for internal pods, NodePort for external pods
  type: NodePort
